### ISSUE TITLE
Installationsfehler

### ISSUE THREAD

**Issue by csaeum** [47gn/contao_cleverreach_sync#1]
Ich habe euer Modul unter system/modules reingeladen. 

Ich finde es nur danach nirgends, arbeite von meiner Seite mit composer wenn ich dort auf Paket aktualisieren gehe bekomme ich folgenden Fehler:

The module dependencies could not be resolved.

Array
(
    [47_cleverreach] => Array
        (
            [0] => core
            [1] => _autoload
        )

)

Ich habe Contao 3.4.5 am laufen mit composer.

**Comment by sgn-dev** [comment]
Hallo,

wir haben das Modul leider noch nicht für die Installation/Aktualisierung über Composer umgestellt. Im Moment ist nur eine manuelle Installation möglich.

Du "siehst" das Modul jetzt nicht direkt im Backen. Allerdings solltest du nach einer erfolgreichen Installation z.B. in den Contao Einstellungen einen neuen Punk "Synchronisation mit cleverreach.de" finden. Vielleicht hilft dir unsere Anleitung unter http://www.47gradnord.de/unternehmen/modulentwicklung.html

**Comment by csaeum** [comment]
Sehen tut man es nicht. 

Es kommt nirgends was vor. Wenn ich aber in den Composer gehe und Datenbank aktualisieren mache oder Pakete aktualisieren dann kommt der oben genannte Fehler.

Schade habe lange schon sowas gesucht.

**Comment by sgn-dev** [comment]
Okay, hast Du den Namespace-ClassLoader installiert? https://github.com/terminal42/contao-NamespaceClassLoader 

Der ist als einzige Abhängigkeit definiert. Wie gesagt, dann sollte es eigentlich laufen. Das Zusammenwirken mit dem Composer kann ich aktuell noch  nicht bewerten. Ich beabsichtige aber, die Installation über den Composer einzubauen.

**Comment by csaeum** [comment]
Ja der wird von anderen über Composer installierten Anwendungen auch gebraucht.

**Comment by sgn-dev** [comment]
Hast du den internen Cache gelöscht? Wenn das nichts bringt, dann fällt mir erst einmal nichts mehr ein :( . Ich müsste es dann mal versuchen lokal nachzubauen...

**Comment by csaeum** [comment]
Ja im neueren Composer wird das ja danach immer sofort verlangt. Also Cache war leer usw.

**Comment by sgn-dev** [comment]
Dann bin ich mit meinem Latein erst mal am Ende :( Wie gesagt, mir fehlt noch Erfahrung im Umgang mit dem Composer. Ich werde schauen, dass ich zeitnah die Installation via Composer hinbekomme. Dann kann ich hoffentlich das von die geschilderte Problem nachvollziehen.

**Comment by csaeum** [comment]
Ok Super :)

**Comment by csaeum** [comment]
Ok habe es heute nochmal probiert da das Avisota Projekt keine weiteren Fortschritte gemacht.

Wie schon geschrieben war die Abhängigkeit gegeben. Euer Paket habe ich reinkopiert und dann nochmal den Cache gekillt.

Nach einen weiteren Besuch in der Paketverwaltung und das aktualisieren der Datenbank scheint es nun zu laufen.

**Comment by sgn-dev** [comment]
Hi,
freut mich dass es klappt. Sorry das ich noch nicht dazu gekommen bin, mich mit der Distribution über den Composer zu befassen. Muss ich aber wegen eines anderen Projektes eh mal dran, von daher kommt da sicherlich noch was meinerseits :)

Wegen Avisota bin ich nicht wirklich auf dem laufenden - ja schade wenn es so ist.

Ich habe im Moment noch ein paar Dinge als Ideen bzw. zur Umsetzung am laufen... vielleicht ist ja da noch was brauchbares für die Allgemeinheit dabei...
