### ISSUE TITLE
Fehler beim speichern eines neuen Verteilers in Contao

### ISSUE THREAD

**Issue by csaeum** [47gn/contao_cleverreach_sync#2]
Ich bekomme folgenden Fehler wenn ich einen neuen Verteiler anlege und diesen abspeichern.
Es kommt auch der Fehler wenn ich den Hacken bei Sync mit CR nicht drin habe.

Fatal error: Uncaught exception SoapFault with message SoapClient::SoapClient(): 'location' and 'uri' options are required in nonWSDL mode thrown in system/modules/47_cleverreach/library/Cleverreach/SOAP/CleverReach.php on line 37
#0 system/modules/47_cleverreach/library/Cleverreach/SOAP/CleverReach.php(37): SoapClient->SoapClient(NULL)
#1 system/modules/47_cleverreach/library/Cleverreach/Backend/Newsletter/Channel/Callback.php(28): Cleverreach\SOAP\CleverReach->__construct()
#2 system/modules/core/library/Contao/System.php(140): Cleverreach\Backend\Newsletter\Channel\Callback->__construct()
#3 system/modules/core/drivers/DC_Table.php(2032): Contao\System->import('Cleverreach\Bac...')
#4 system/modules/core/classes/Backend.php(650): Contao\DC_Table->edit()
#5 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('newsletter')
#6 contao/main.php(20): Contao\BackendMain->run()
#7 {main}

**Comment by sgn-dev** [comment]
Hallo,

danke für die Nachricht. 

Ich konnte deinen Fehler nachvollziehen. Du musst in den Contao Einstellung die URL zur Schnittstelle von Cleverreach sowie deinen persönlichen API-Key eintragen. Wenn du das drin hast, dann sollte der beschriebene Fehler nicht mehr kommen.

![bildschirmfoto 2015-09-23 um 21 23 41](https://cloud.githubusercontent.com/assets/10742053/10056035/b5742a56-6239-11e5-883a-329c877e93a0.png)

Das dieser Fehler auch dann kommt, wenn der Haken für das Synchronisieren nicht gesetzt ist, scheint ein Bug zu sein. Wird natürlich behoben, ich denke morgen komme ich dazu.

**Comment by sgn-dev** [comment]
Hallo,
konntest du das Problem lösen? Funktioniert nun das Synchronisieren wenn die WDSL-Url und der API-Key eingetragen ist?
