### ISSUE TITLE
Class 'CleverreachSync' not found in .../classes/Backend.php

### ISSUE THREAD

**Issue by torschiff** [47gn/contao_cleverreach_sync#3]
Hallo,

ich nutze 3.44 und habe den aktuellen NamespaceClassLoader drauf. Leider bekomme ich beim Versuch der Synchronisierung eine weiße Seite. 
Im Error-Log steht folgendes: 
PHP Fatal error: Class 'CleverreachSync' not found in ...system/modules/core/classes/Backend.php on line 412

Vielen Dank für eure Hilfe

**Comment by sgn-dev** [comment]
Hallo,

hast du den internen Cache geleert bzw. es so eingestellt, das dieser Umgangen wird?

Hast du in den Einstellung von Contao die WDSL Url und deinen API-Key von CleverReach hinterlegt?

Was komisch ist, das es eigentlich die Klasse CleverreachSync garnicht gibt :) Die Klasse die das Handling mit Cleverreach macht heißt nur CleverReach.

Viele Grüße

**Comment by sgn-dev** [comment]
Noch was vergessen... Datenbank-Update auch gemacht?
Bei welcher Aktion genau kam die weiße Seite? Was wolltest du synchronisieren? Verteiler oder Abonnement ?

**Comment by torschiff** [comment]
Fehler gefunden - es waren Reste eines anderen Cleverreach-Moduls noch aktiv - jetzt läuft alles. 

Trotzdem vielen Dank

Viele Grüße

**Comment by sgn-dev** [comment]
Gerne :)
