### ISSUE TITLE
Fehler bei Datenübertragung

### ISSUE THREAD

**Issue by simonbuchwitz** [47gn/contao_cleverreach_sync#4]
Wenn ich unter "Neuen Verteiler" bei "Diesen Verteiler mit cleverreach.de synchronisieren?" den Hacken setze, erscheint die Meldung "Die Daten werden geladen …" aber der Vorgang geht von hier an nicht weiter.
Wenn ich den Hacken nicht setze Erschein folgender Fehler:
Query error: Unknown column 'clr_do_synchronize' in 'field list' (UPDATE tl_newsletter_channel SET clr_do_synchronize='' WHERE id='11')

Den WDSL-URL und den API-Key habe ich wie beschrieben eingefügt.

Beste Grüße
Simon Buchwitz

**Comment by sgn-dev** [comment]
Hallo Simon,

Hast du ein Datenbank-Update gemacht?

Viele Grüße
Holger Neuner

Von meinem iPhone gesendet

Am 26.11.2015 um 10:00 schrieb simonbuchwitz <notifications@github.com<mailto:notifications@github.com>>:

Wenn ich unter "Neuen Verteiler" bei "Diesen Verteiler mit cleverreach.dehttp://cleverreach.de synchronisieren?" den Hacken setze, erscheint die Meldung "Die Daten werden geladen ..." aber der Vorgang geht von hier an nicht weiter.
Wenn ich den Hacken nicht setze Erschein folgender Fehler:
Query error: Unknown column 'clr_do_synchronize' in 'field list' (UPDATE tl_newsletter_channel SET clr_do_synchronize='' WHERE id='11')

Den WDSL-URL und den API-Key habe ich wie beschrieben eingefügt.

Beste Grüße
Simon Buchwitz

##

**Comment by simonbuchwitz** [comment]
Hallo Holger,

danke für die schnelle Antwort.
nicht das ich wüsste... ist das erforderlich?

**Comment by sgn-dev** [comment]
Jap :) Bitte machen, dann in der Systemwartung den internen Cache löschen, dann sollte eigentlich alles passen.

Viele Grüße

Holger Neuner

[logo47gradnord_signatur]

47GradNord
Agentur für Internetlösungen
Inhaber: Holger Neuner

Humpisstraße 12/1
88239 Wangen im Allgäu

T: +49 (0)7528 975 6553
M: +49 (0)171 2826166
E: mailto:neuner@47gradnord.de

---

St.-Nr.: 91325/27098
Inhaber:     Holger Neuner

Diese Email kann vertrauliche Informationen enthalten. Wenn Sie nicht der richtige
Adressat  sind  oder diese  Email  irrtümlich  erhalten  haben, informieren  Sie  bitte
sofort den Absender und vernichten Sie diese Email. Das unerlaubte Kopieren sowie
die unbefugte Weitergabe dieser Mail  ist  nicht gestattet. Wir  haben alle verkehrs-
üblichen Maßnahmen unternommen, um das Risiko der Verbreitung virenbefallener
Software oder Emails zu minimieren. Daher  schließen  wir  die Haftung für jeglichen
Verlust oder Schäden durch virenbefallene Software oder Emails aus.

Von: simonbuchwitz <notifications@github.com<mailto:notifications@github.com>>
Antworten an: 47gn/contao_cleverreach_sync <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 26. November 2015 10:19
An: 47gn/contao_cleverreach_sync <contao_cleverreach_sync@noreply.github.com<mailto:contao_cleverreach_sync@noreply.github.com>>
Cc: Holger Neuner <neuner@47gradnord.de<mailto:neuner@47gradnord.de>>
Betreff: Re: [contao_cleverreach_sync] Fehler bei Datenübertragung (#4)

Hallo Holger,

danke für die schnelle Antwort.
nicht das ich wüsste... ist das erforderlich?

##

**Comment by simonbuchwitz** [comment]
Hat geklappt.

Vielen Dank für die Hilfe :-)

**Comment by sgn-dev** [comment]
Gerne :)

Viele Grüße

Holger Neuner

[logo47gradnord_signatur]

47GradNord
Agentur für Internetlösungen
Inhaber: Holger Neuner

Humpisstraße 12/1
88239 Wangen im Allgäu

T: +49 (0)7528 975 6553
M: +49 (0)171 2826166
E: mailto:neuner@47gradnord.de

---

St.-Nr.: 91325/27098
Inhaber:     Holger Neuner

Diese Email kann vertrauliche Informationen enthalten. Wenn Sie nicht der richtige
Adressat  sind  oder diese  Email  irrtümlich  erhalten  haben, informieren  Sie  bitte
sofort den Absender und vernichten Sie diese Email. Das unerlaubte Kopieren sowie
die unbefugte Weitergabe dieser Mail  ist  nicht gestattet. Wir  haben alle verkehrs-
üblichen Maßnahmen unternommen, um das Risiko der Verbreitung virenbefallener
Software oder Emails zu minimieren. Daher  schließen  wir  die Haftung für jeglichen
Verlust oder Schäden durch virenbefallene Software oder Emails aus.

Von: simonbuchwitz <notifications@github.com<mailto:notifications@github.com>>
Antworten an: 47gn/contao_cleverreach_sync <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 26. November 2015 10:26
An: 47gn/contao_cleverreach_sync <contao_cleverreach_sync@noreply.github.com<mailto:contao_cleverreach_sync@noreply.github.com>>
Cc: Holger Neuner <neuner@47gradnord.de<mailto:neuner@47gradnord.de>>
Betreff: Re: [contao_cleverreach_sync] Fehler bei Datenübertragung (#4)

Hat geklappt.

Vielen Dank für die Hilfe :-)

##
