### ISSUE TITLE
Fehlermeldung nach Installation

### ISSUE THREAD

**Issue by omuellersch** [47gn/contao_cleverreach_sync#5]
Nach Download, entpacken und übertragen des Ordners 47_cleverreach in das Verzeichnis /modules bekomme ich beim nächsten Seitenaufruf diese Meldung: 

The module dependencies could not be resolved.

Array
(
    [47_cleverreach] => Array
        (
            [0] => core
            [1] => _autoload
        )

)

**Comment by sgn-dev** [comment]
Hallo,

Ist die Erweiterung https://contao.org/de/erweiterungsliste/view/NamespaceClassLoader.de.html installiert? Die wird von dem Modul benötigt.

Nach der Installation sicherheitshalber nochmal den internen Cache löschen, ein Datenbank-Update machen und dann sollte es eigentlich funktionieren.

Viele Grüße

Holger Neuner

Von: freiwild <notifications@github.com<mailto:notifications@github.com>>
Antworten an: 47gn/contao_cleverreach_sync <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Dienstag, 26. April 2016 10:48
An: 47gn/contao_cleverreach_sync <contao_cleverreach_sync@noreply.github.com<mailto:contao_cleverreach_sync@noreply.github.com>>
Betreff: [47gn/contao_cleverreach_sync] Fehlermeldung nach Installation (#5)

Nach Download, entpacken und übertragen des Ordners 47_cleverreach in das Verzeichnis /modules bekomme ich beim nächsten Seitenaufruf diese Meldung:

The module dependencies could not be resolved.

Array
(
[47_cleverreach] => Array
(
[0] => core
[1] => _autoload
)

)

**Comment by omuellersch** [comment]
Den NameSpaceClassLoader hatte ich installiert. Contao 3.5.9 läuft mit deaktiviertem Cache.
Zu einer DB-Aktualisierung hatte ich gar keine Gelegenheit, da bei jedem Seitenaufruf die o.g. Meldung kommt, auch bei der install.php.

Danke für die schnelle Reaktion!

**Comment by sgn-dev** [comment]
okay, dann vielleicht nochmal das Cleverreach-Modul kurz aus dem Module-Ordner entfernen, schauen dass die NameSpaceClassLoader-Erweiterung sauber drin ist und danach nochmal das Cleverreach-Modul einspielen.

Wir geben in unserem Modul eben vor, dass der NameSpaceClassLoader erforderlich ist. Die o.g Fehlermeldung besagt eigentlich, dass Contao die Abhängigkeiten nicht auflösen kann. Von daher liegt die Vermutung schon nahe, dass ewas mit dem Classloader noch nicht passt.

Bitte mal versuchen und nochmal kurz Rückmeldung geben.

Viele Grüße
Holger Neuner

**Comment by omuellersch** [comment]
habe das Cleverreach-Modul entfernt - und bekomme promt folgende Meldung:
`Warning: require_once(/www/htdocs/w0120014/installcontao/contao3/system/modules/_autoload/NamespaceClassLoader.php): failed to open stream: No such file or directory in system/modules/contao-NamespaceClassLoader-master/config/autoload.php on line 29

#0 system/modules/contao-NamespaceClassLoader-master/config/autoload.php(29): __error(2, 'require_once(/w...', '/www/htdocs/w01...', 29, Array)
#1 system/modules/contao-NamespaceClassLoader-master/config/autoload.php(29): require_once()
#2 system/modules/core/library/Contao/ClassLoader.php(222): include('/www/htdocs/w01...')
#3 system/initialize.php(105): Contao\ClassLoader::scanAndRegister()
#4 contao/main.php(16): require('/www/htdocs/w01...')
#5 {main}
`

Fatal error: require_once(): Failed opening required '/www/htdocs/w0120014/installcontao/contao3/system/modules/_autoload/NamespaceClassLoader.php' (include_path='.:/usr/share/php:..') in /www/htdocs/w0120014/installcontao/contao3/system/modules/contao-NamespaceClassLoader-master/config/autoload.php on line 29`

**Comment by sgn-dev** [comment]
puh... da hat es irgendwas zerbröselt....

Schick mir doch mal per Mail die URL sowie die FTP-Zugangsdaten. Dann schau ich mal drauf...
neuner@47gradnord.de

**Comment by omuellersch** [comment]
Mach ich. Danke!

**Comment by sgn-dev** [comment]
Mach bitte mal ein DB-Update. Der NamespaceClassLoader ist drin, sowie unser Cleverreach-Modul. Das sollte eigentlich passen. In den Einstellungen z.B siehst du am Ende der Seite die neuen Einträge für den API-Key usw.

Nach dem DB-Update sollte es nun eigentlich funzen :)

**Comment by omuellersch** [comment]
Super - Vielen Dank! Wo lag das Problem?

**Comment by sgn-dev** [comment]
Vodoo ?

Ne keine Ahnung... ich habe lediglich von mir lokal das Modul mit dem Namespace-Class-Loader eingespielt. Danach geschaut ob es zu einem Fehler kommt. Dem war nicht der Fall. Danach habe ich das Cleverreach-Modul eingespielt und geschaut ob dann ein Fehler kommt.

Freut mich, wenn es jetzt passt :)

Viel Spass damit...

**Comment by csaeum** [comment]
Ist geplant das Tool für Composer und für Contao 4 startklar zu machen?

**Comment by sgn-dev** [comment]
Hallo Christian,

geplant schon, aber leider fehlt mir die Zeit im Moment dazu ☹ und auch der konkrete Anlass. Ich setze selbst das Modul im Moment nur bei 3.5er Projekten ein.

Viele Grüße

Holger Neuner

Von: Christian Säum notifications@github.com
Antworten an: 47gn/contao_cleverreach_sync reply@reply.github.com
Datum: Donnerstag, 16. Juni 2016 22:48
An: 47gn/contao_cleverreach_sync contao_cleverreach_sync@noreply.github.com
Cc: Holger Neuner neuner@47gradnord.de, Comment comment@noreply.github.com
Betreff: Re: [47gn/contao_cleverreach_sync] Fehlermeldung nach Installation (#5)

Ist geplant das Tool für Composer und für Contao 4 startklar zu machen?
