### ISSUE TITLE
Erste Synchronisierung der Verteilerlisten klappt nicht

### ISSUE THREAD

**Issue by michael-hillmann** [47gn/contao_cleverreach_sync#6]
Hallo,

erstmal Danke für das tolle PlugIn! Synchronisierung läuft nach anfänglichen Hürden prima.

Eine Anmerkung:
In meiner Contao 3.5.15 Installation hatte ich Probleme mit der initialen Synchronisierung der bereits bestehenden Verteilerlisten. Die Checkboxen für das Synchronisieren ("Mit cleverreach.de synchronisieren?") musste ich für alle Kontakte von Hand setzen - war bei über 3.000 Kontakten etwas mühsam ;-))

Gruß
Michael

**Comment by sgn-dev** [comment]
Hallo Michael,

danke fürs Feedback.

Ja in der Tat ist die Erweiterung im Moment nicht unbedingt dafür gebaut, mit bereits bestehenden Kontakten zu arbeiten. Der Workflow war erstmal nur auf den Aufbau einer neuen Liste gerichtet. Von daher gebe ich dir recht - das ist ist etwas mühsam :) Mal schauen, vielleicht ergibt sich ja hier mal noch ein Ausbau...

Grüße
Holger

**Comment by michael-hillmann** [comment]
Ok. Danke für die Info. Dann ist ja alles nach Plan verlaufen ;-))
